name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.1
    - uses: cachix/install-nix-action@v20
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v12
      with:
        name: csdc
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build release.nix
